Pi-dev finale/src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", length=255)
     */
    private $id_client;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 1,
     *      max = 20,
     *      minMessage = "Le nom  doit comporter au moins {{ limit }} caractères",
     *      maxMessage = "Le nom  doit comporter au plus {{ limit }} caractères"
     * )
     */
    private $nom;

    /**
        
     * @ORM\Column(type="string", length=30)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 1,
     *      max = 20,
     *      minMessage = "Le nom  doit comporter au moins {{ limit }} caractères",
     *      maxMessage = "Le nom  doit comporter au plus {{ limit }} caractères"
     * )
     */
    
    private $prenom;

     /**
     * @ORM\Column(type="string", length=8)
     * @Assert\NotBlank
     * @Assert\Length(
     *  value = 8,
     *  exactMessage = "Le numéro du téléphone doit comporter 8 caractères"
     * )

     */
    private $numtel;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Saisir l'immatricule ")
     */
    private $voitmat;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Saisir la valeur de l'instamonaie de client")
     */
    private $instamon;

    /**
     * @ORM\Column(type="string", length=255 ,unique=true)
     * @Assert\NotBlank(message="Saisir le login ")
     * @Assert\Email(message = "The email '{{ value }}' is not a valid email.")
     */
    private $login;

     /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\NotCompromisedPassword(
     * message= "Ce mot de passe doit comporter au moins une lettre majuscule et au moins une lettre minuscule"
               
     * )
     *  @Assert\Length(
     *      min = 8,
     *      max = 20,
     *   minMessage = "Le mot de passe  doit comporter au moins {{ limit }} caractères",
     *   maxMessage = "Le mot de passe  doit comporter au plus {{ limit }} caractères"         
     * )
    
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=Client::class, mappedBy="parking")
     */
    private $parking;

    /**
     * @ORM\OneToMany(targetEntity=Client::class, mappedBy="admin")
     */
    private $admin;
    
    public function getId(): ?int
    {
        return $this->id_client;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumtel(): ?string
    {
        return $this->numtel;
    }

    public function setNumtel(string $numtel): self
    {
        $this->numtel = $numtel;

        return $this;
    }

    public function getVoitmat(): ?string
    {
        return $this->voitmat;
    }

    public function setVoitmat(string $voitmat): self
    {
        $this->voitmat = $voitmat;

        return $this;
    }

    public function getInstamon(): ?float
    {
        return $this->instamon;
    }

    public function setInstamon(float $instamon): self
    {
        $this->instamon = $instamon;

        return $this;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getParking(): ?Parking
    {
        return $this->parking;
    }

    public function setParking(?Parking $parking): self
    {
        $this->parking = $parking;

        return $this;
    }

    
    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(?Admin $admin): self
    {
        $this->admin = $admin;

        return $this;
    }
}

Pi-dev finale/src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('nom', TextType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('prenom', TextType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('numtel', TextType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('voitmat', TextType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('instamon', TextType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('login', EmailType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('password', PasswordType::class,[
                'attr' => ['class' => 'form-control'],
            ])
            ->add('status', TextType::class,[
                'attr' => ['class' => 'form-control'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

Pi-dev finale/src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="app_client", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('app_client', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_client}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id_client}/edit", name="client_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Client $client, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_client', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_client}", name="client_delete", methods={"POST"})
     */
    public function delete(Request $request, Client $client, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_client', [], Response::HTTP_SEE_OTHER);
    }
}

Pi-dev finale/templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id_client': client.id}) }}" onsubmit="return confirm('Voulez vous supprimez ce client ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn">Supprimer</button>
</form>

Pi-dev finale/templates/client/_form.html.twig
{{ form_start(form) }}
<tr ><td>Nom</td><td>{{ form_widget(form.nom) }}</td>
    <td class="text-danger">{{ form_errors(form.nom) }} </td>
</tr>
<tr><td>Prénom</td><td>{{ form_widget(form.prenom) }}</td>
    <td class="text-danger">{{ form_errors(form.prenom) }} </td>
</tr>
<tr><td>N°Télephone</td><td>{{ form_widget(form.numtel) }}</td>
    <td class="text-danger">{{ form_errors(form.numtel) }} </td>
</tr>
<tr><td>Immatricule voiture</td><td>{{ form_widget(form.voitmat) }}</td>
    <td class="text-danger">{{ form_errors(form.voitmat) }} </td>
</tr>
<tr><td>Valeur instamonnaie</td><td>{{ form_widget(form.instamon) }}</td>
    <td class="text-danger">{{ form_errors(form.instamon) }} </td>
</tr>
<tr><td>Email</td><td>{{ form_widget(form.login) }}</td>
    <td class="text-danger">{{ form_errors(form.login) }} </td>
</tr>
<tr><td>Mot De Passe</td><td>{{ form_widget(form.password) }}</td>
    <td class="text-danger">{{ form_errors(form.password) }} </td>
</tr>
<tr><td>Status</td><td>{{ form_widget(form.status) }}</td>
    <td class="text-danger">{{ form_errors(form.status) }} </td>
</tr>
</table>
<br>
<div class="text-center">
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
</div>

{{ form_end(form) }}

Pi-dev finale/templates/client/edit.html.twig
{% extends'baseBack.html.twig' %}
{% block body %}
    <div class="content-wrapper">
        <div class="container-fluid">

            <div class="row mt-3">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped">


                                {{ include('client/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_client') }}">Liste des clients</a>

    {{ include('client/_delete_form.html.twig') }}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Pi-dev finale/templates/client/index.html.twig
{% extends'baseBack.html.twig' %}
{% block body %}
    <div class="content-wrapper">
        <div class="container-fluid">

            <div class="row mt-3">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Liste des clients</h5>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>

                                    <tr>
                                        <th>ID client</th>
                                        <th>Nom</th>
                                        <th>Prénom</th>
                                        <th>Numéro de télephone</th>
                                        <th>Immatricule voiture</th>
                                        <th>Insta monaie</th>
                                        <th>Login</th>
                                        <th>Password</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for client in clients %}
                                        <tr>
                                            <td>{{ client.id }}</td>
                                            <td>{{ client.nom }}</td>
                                            <td>{{ client.prenom }}</td>
                                            <td>{{ client.numtel }}</td>
                                            <td>{{ client.voitmat }}</td>
                                            <td>{{ client.instamon }}</td>
                                            <td>{{ client.login }}</td>
                                            <td>{{ client.password }}</td>
                                            <td>{{ client.status }}</td>
                                            <td>
                                                <a href="{{ path('client_show', {'id_client': client.id}) }}">show</a>
                                                <a href="{{ path('client_edit', {'id_client': client.id}) }}">edit</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="10">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </div>
                    <a href="{{ path('client_new') }} " style="float: right;">Créer Nouveau client</a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Pi-dev finale/templates/client/new.html.twig
{% extends'baseBack.html.twig' %}
{% block body %}
<div class="content-wrapper">
    <div class="container-fluid">

        <div class="row mt-3">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Liste des clients</h5>
                        <div class="table-responsive">
                            <table class="table table-striped">

                                {{ include('agent_service/_form.html.twig') }}
                                <a href="{{ path('app_agentservice') }}">Liste des clients</a>
                                    </table>


    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </body>

{% endblock %}

Pi-dev finale/templates/client/show.html.twig
{% extends'baseBack.html.twig' %}
{% block body %}
    <div class="content-wrapper">
        <div class="container-fluid">

            <div class="row mt-3">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Liste des clients</h5>
                            <div class="table-responsive">
                                <table class="table table-striped">

        <tbody>
            <tr>
                <th>Id client</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ client.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ client.prenom }}</td>
            </tr>
            <tr>
                <th>Numéro de télephone</th>
                <td>{{ client.numtel }}</td>
            </tr>
            <tr>
                <th>Immatricule voiture</th>
                <td>{{ client.voitmat }}</td>
            </tr>
            <tr>
                <th>Insta monnaie</th>
                <td>{{ client.instamon }}</td>
            </tr>
            <tr>
                <th>Login</th>
                <td>{{ client.login }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ client.password }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ client.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_client') }}">Liste des clients </a>



    {{ include('client/_delete_form.html.twig') }}


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}